# Generated by Django 4.2 on 2025-04-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_rename_organization_id_possales_organisation_id'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('external_name', models.CharField(blank=True, max_length=255, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('organisation', 'name')},
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organisation'], name='core_site_organis_833164_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['name'], name='core_site_name_97584f_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['status'], name='core_site_status_5592a0_idx'),
        ),
        migrations.AddField(
            model_name='integrationsitemapping',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration'),
        ),
        migrations.AddField(
            model_name='integrationsitemapping',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_mappings', to='core.site'),
        ),
        migrations.AddIndex(
            model_name='integrationsitemapping',
            index=models.Index(fields=['site', 'integration'], name='core_integr_site_id_fe64b5_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsitemapping',
            index=models.Index(fields=['external_id'], name='core_integr_externa_8f6bb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationsitemapping',
            unique_together={('site', 'integration', 'external_id')},
        ),
    ]
