# Generated by Django 4.2 on 2025-04-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commentary_commentary_core_commen_site_id_bbb827_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('reviewer', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Stores review parameters and their ratings in a flexible format')),
                ('recommend_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('visit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source_system', models.CharField(max_length=255)),
                ('automation', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.site')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_id'], name='core_review_review__6aa78e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_date'], name='core_review_review__affdb7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['client_name'], name='core_review_client__4dc95d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['store_name'], name='core_review_store_n_793846_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['city'], name='core_review_city_6e1798_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['site'], name='core_review_site_id_523261_idx'),
        ),
    ]
