# Generated by Django 4.2 on 2025-04-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review_review_core_review_review__6aa78e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.CharField(max_length=50)),
                ('calendar_type', models.CharField(max_length=50)),
                ('fiscal_year', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=50)),
                ('month_sort', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_calendars', to='core.client')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='bulk_calendar',
            index=models.Index(fields=['client'], name='core_bulk_c_client__92093e_idx'),
        ),
        migrations.AddIndex(
            model_name='bulk_calendar',
            index=models.Index(fields=['date'], name='core_bulk_c_date_b0f70e_idx'),
        ),
        migrations.AddIndex(
            model_name='bulk_calendar',
            index=models.Index(fields=['fiscal_year'], name='core_bulk_c_fiscal__5b5cc5_idx'),
        ),
    ]
