# Generated by Django 4.2 on 2025-04-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integrations', '0002_possales_alter_integration_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature_value', models.FloatField()),
                ('temperature_unit', models.CharField(max_length=10)),
                ('pressure_value', models.FloatField()),
                ('pressure_unit', models.CharField(max_length=10)),
                ('relative_humidity', models.FloatField()),
                ('wind_speed_value', models.FloatField()),
                ('wind_speed_unit', models.CharField(max_length=10)),
                ('wind_direction_degrees', models.FloatField()),
                ('windgust_speed_value', models.FloatField(blank=True, null=True)),
                ('windgust_speed_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('cloudiness', models.IntegerField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('rain', models.FloatField(blank=True, null=True)),
                ('snow', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('record_date', models.DateTimeField()),
                ('source_system', models.CharField(max_length=50)),
                ('automation', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('masking_policy', models.CharField(blank=True, max_length=50, null=True)),
                ('action_group', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_records', to='core.client')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_records', to='core.organisation')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_records', to='core.site')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['client_name'], name='integration_client__5fd057_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['store_name'], name='integration_store_n_1a1ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['city'], name='integration_city_4e69ed_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['record_date'], name='integration_record__4e074a_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['status'], name='integration_status_0ac558_idx'),
        ),
    ]
