# Generated by Django 4.2 on 2025-04-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_weather_weather_integration_client__5fd057_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possales',
            old_name='organization_id',
            new_name='organisation_id',
        ),
    ]
