# Generated by Django 4.2 on 2025-04-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integrationsitemapping_site_address_line1_and_more'),
        ('integrations', '0004_rename_organization_id_possales_organisation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toastorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toast_orders', to='core.site'),
        ),
        migrations.AlterField(
            model_name='toastdayschedule',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site'),
        ),
        migrations.AlterField(
            model_name='toastjoinedopeninghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site'),
        ),
        migrations.AlterField(
            model_name='toastweeklyschedule',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site'),
        ),
        migrations.AddIndex(
            model_name='toastorder',
            index=models.Index(fields=['site'], name='integration_site_id_4ed043_idx'),
        ),
    ]
