# Generated by Django 4.2 on 2025-04-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_toastorder_site_alter_toastdayschedule_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='netsuite_account_id',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='netsuite_certificate_id',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='netsuite_client_id',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='netsuite_client_secret',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='netsuite_consumer_key',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='netsuite_private_key',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='org',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='toast_api_url',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='toast_client_id',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='toast_client_secret',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='xero_client_id',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='xero_client_secret',
        ),
    ]
