# Generated by Django 4.2 on 2025-04-22 00:00

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_remove_integration_netsuite_account_id_and_more'),
    ]

    operations = [
        # Add payments field to ToastOrder if it doesn't already exist
        migrations.AddField(
            model_name='toastorder',
            name='payments',
            field=models.JSONField(blank=True, help_text='Raw payment data from Toast', null=True),
        ),
        
        # Create ToastPayment model
        migrations.CreateModel(
            name='ToastPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_guid', models.CharField(db_index=True, max_length=255)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('order_guid', models.CharField(db_index=True, max_length=255)),
                ('restaurant_guid', models.CharField(db_index=True, max_length=255)),
                ('check_guid', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('last4_digits', models.CharField(blank=True, max_length=10, null=True)),
                ('paid_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_business_date', models.IntegerField(blank=True, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('card_entry_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('server_guid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toast_payments', to='integrations.integration')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant_id', 'order_guid'], name='integration_tenant_i_b2c3b6_idx'),
                    models.Index(fields=['tenant_id', 'restaurant_guid'], name='integration_tenant_i_c67fbe_idx'),
                    models.Index(fields=['tenant_id', 'paid_business_date'], name='integration_tenant_i_e8b121_idx'),
                    models.Index(fields=['tenant_id', 'payment_status'], name='integration_tenant_i_5f4b31_idx'),
                ],
                'unique_together': {('tenant_id', 'payment_guid')},
            },
        ),
    ]