# Generated by Django 4.2 on 2025-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_add_toast_payment_and_fix_toast_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroaccountsraw',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xerobanktransactionsraw',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xerobudgetsraw',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
