# Generated by Django 4.2 on 2025-04-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_rename_integration_tenant_i_b2c3b6_idx_integration_tenant__32a224_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='currency_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='line_amount_types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='line_item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='source_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='tax_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelineitems',
            name='tenant_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
