# Generated by Django 4.2 on 2025-04-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_rename_integration_tenant_i_b2c3b6_idx_integration_tenant__32a224_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highprioritytask',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highprioritytask',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
