# Generated by Django 4.2 on 2025-05-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_netsuitegeneralledger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netsuitegeneralledger',
            old_name='tenant_id',
            new_name='tenant',
        ),
    ]
