# Generated by Django 4.2 on 2025-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_rename_tenant_id_netsuitegeneralledger_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsuitegeneralledger',
            name='debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
