# Generated by Django 4.2 on 2025-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_netsuitegeneralledger_debit_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='netsuitegeneralledger',
            index=models.Index(fields=['tenant_id', 'transaction_id', 'transaction_line_id'], name='integration_tenant__377241_idx'),
        ),
        migrations.AddIndex(
            model_name='netsuitegeneralledger',
            index=models.Index(fields=['tenant_id', 'line_unique_key'], name='integration_tenant__a1a712_idx'),
        ),
    ]
