# Generated by Django 4.2 on 2025-05-22 19:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_netsuitegeneralledger_integration_tenant__377241_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToastRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_guid', models.CharField(blank=True, max_length=255, null=True)),
                ('order_guid', models.CharField(db_index=True, max_length=255)),
                ('check_guid', models.CharField(db_index=True, max_length=255)),
                ('payment_guid', models.CharField(db_index=True, max_length=255)),
                ('refund_guid', models.CharField(db_index=True, max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tip_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refund_business_date', models.IntegerField(blank=True, null=True)),
                ('refund_transaction_guid', models.CharField(blank=True, null=True)),
                ('refund_transaction_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toast_refunds', to='integrations.integration')),
            ],
        ),
    ]
