# Generated by Django 4.2 on 2025-05-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_toastrefund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toastrefund',
            name='integration',
        ),
    ]
