name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add droplet to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Sync code to VPS
      run: |
        rsync -az --delete \
          --exclude '.git*' \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/insights/

    - name: Upload .env
      run: |
        echo "Creating .env file with individual secrets..."
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cat > /var/www/insights/.env" << 'EOL'
        SECRET_KEY=${{ secrets.SECRET_KEY }}
        DEBUG=${{ secrets.DEBUG }}
        ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
        DB_NAME=${{ secrets.DB_NAME }}
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_HOST=${{ secrets.DB_HOST }}
        DB_PORT=${{ secrets.DB_PORT }}
        DB_SSL_MODE=${{ secrets.DB_SSL_MODE }}
        BACKEND_URL=${{ secrets.BACKEND_URL }}
        ENVIRONMENT=${{ secrets.ENVIRONMENT }}
        CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
        CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }}
        CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}
        EOL

    - name: Verify .env file
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
        cd /var/www/insights
        echo "Verifying .env file..."
        if [ ! -s ".env" ]; then
          echo "ERROR: .env file is empty!"
          exit 1
        fi
        
        echo "File size: $(wc -c < .env) bytes"
        echo "Number of lines: $(wc -l < .env) lines"
        echo "First few variable names in .env:"
        grep -v '^#' .env | cut -d'=' -f1 | head -n 5
        ENDSSH

    - name: Remote deploy commands
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'EOSSH'
        set -e
        cd /var/www/insights
        # Verify .env file before proceeding
        echo "Verifying .env file..."
        if [ ! -f ".env" ]; then
          echo "ERROR: .env file not found in $(pwd)"
          exit 1
        fi
        
        echo "Content of .env directory:"
        ls -la .env

                
        echo "Ensuring static directory exists..."
        if [ ! -d "static" ]; then
          echo "Creating static directory..."
          mkdir -p static
          chmod 755 static
        fi

        
        echo "Skipping git pull as files were synced with rsync..."
        
        echo "Checking virtual environment..."
        if [ ! -d "venv" ]; then
          echo "Creating virtual environment..."
          python3 -m venv venv
        fi
        
        echo "Activating virtual environment..."
        source venv/bin/activate

        echo "Installing dependencies..."
        pip install -r requirements/requirements.txt

        echo "Running migrations..."
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput

        echo "Collecting static files..."
        python manage.py collectstatic --noinput

        echo "Restarting Gunicorn..."
        pkill -f "gunicorn config.wsgi:application --bind 0.0.0.0:8000" || true
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --daemon

        echo "Stopping Celery workers..."
        celery -A config control shutdown || true
        sleep 30
        pkill -f celery || true
        pkill -9 -f "celery worker" || true

        echo "Cleaning up stale pidfiles..."
        rm -f /var/run/celery/*.pid /tmp/celerybeat.pid

        echo "Ensuring log directories exist..."
        mkdir -p /var/log/celery
        chmod 777 /var/log/celery
        touch /var/log/celery/worker.log /var/log/celery/worker_high_priority.log \
              /var/log/celery/beat.log   /var/log/celery/flower.log
        chmod 666 /var/log/celery/*.log

        echo "Checking Redis health..."
        if ! redis-cli ping | grep -q PONG; then
          echo "Redis down → restarting..."
          sudo systemctl restart redis
          sleep 5
        fi
        redis-cli flushall || true

        echo "Starting Celery workers..."
        celery -A config worker -n normal_worker@%h      -Q org_sync,celery -c 3 -l info \
               --logfile=/var/log/celery/worker.log --detach
        celery -A config worker -n high_priority_worker@%h -Q high_priority -c 1 -l info \
               --logfile=/var/log/celery/worker_high_priority.log --detach

        echo "Restarting Celery Beat..."
        pkill -f "celery beat -A config" || true
        rm -f /tmp/celerybeat.pid
        celery -A config beat -l info --pidfile=/tmp/celerybeat.pid \
               --logfile=/var/log/celery/beat.log --detach

        echo "Restarting Flower..."
        pkill -f "flower -A config" || true
        sleep 3
        fuser -k 5555/tcp || true
        rm -f /tmp/flower.pid
        nohup venv/bin/celery -A config flower --port=5555 \
              > /var/log/celery/flower.log 2>&1 &

        echo "Waiting for workers to initialise..."
        sleep 10
        celery -A config status
        celery -A config inspect active_queues

        echo "Deployment completed successfully!"
        EOSSH
